routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', \App\Http\Controllers\HomeController::class)->name('home');

//Route::prefix('project')->group(function () {
//    Route::controller(\App\Http\Controllers\ProjectController::class)->group(function () {
//        Route::get('/', 'index')->name('project.index');
//        Route::get('/{project}', 'show')->name('project.show');
//    });
//});


Route::resource('project', \App\Http\Controllers\ProjectController::class);

Route::middleware('auth')->group(function () {
    Route::post('logout', [\App\Http\Controllers\Auth\AuthenticatedController::class, 'destroy'])
        ->name('logout');

    Route::prefix('m')->group(function () {
        Route::get('p/{profile}', [\App\Http\Controllers\Manage\ProfileController::class, 'index'])
            ->name('profile.index');
        Route::put('p/{profile}', [\App\Http\Controllers\Manage\ProfileController::class, 'update'])
            ->name('profile.update');
    });

});

Route::middleware('guest')->group(function () {
    Route::post('login', [\App\Http\Controllers\Auth\AuthenticatedController::class, 'store'])
        ->name('login');
});

app/Models/Profile.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Profile extends Model
{
    use HasFactory, HasUuids;

    protected $guarded = [];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}

app/Models/Project.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Project extends Model
{
    use HasFactory, HasUuids;

    protected $guarded = [];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getAvatar(): string
    {
        return 'https://www.gravatar.com/avatar/'
            . md5($this->email)
            . '?s=200'
            . '&d=retro';
    }

    public function profile(): HasOne
    {
        return $this->hasOne(Profile::class, 'user_id');
    }

    public function projects(): HasMany
    {
        return $this->hasMany(Project::class);
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Profile;

class HomeController extends Controller
{
    public function __invoke()
    {
        return view('profile.index', [
            'profile' => Profile::first(),
        ]);
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreProjectRequest;
use App\Http\Requests\UpdateProjectRequest;
use App\Models\Project;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Storage;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        $projects = Project::query()
            ->select('id', 'name', 'body', 'is_public')
            ->when(!auth()->check(), fn($query) => $query->where('is_public', true))
            ->latest()
            ->paginate(9);

        return view('project.index', [
            'projects' => $projects
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        return view('project.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  StoreProjectRequest  $request
     * @return RedirectResponse
     */
    public function store(StoreProjectRequest $request)
    {
        $project = Project::create($request->validated());

        return to_route('project.show', $project);
    }

    /**
     * Display the specified resource.
     *
     * @param  Project  $project
     * @return Application|Factory|View
     */
    public function show(Project $project)
    {
        if ($project->is_public || auth()->check()) {
            return view('project.show', [
                'project' => $project
            ]);
        } else {
            abort(404);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Project  $project
     * @return Application|Factory|View
     */
    public function edit(Project $project)
    {
        if (!auth()->check()) {
            abort(404);
        }

        return view('project.edit', [
            'project' => $project
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  UpdateProjectRequest  $request
     * @param  Project  $project
     * @return RedirectResponse
     */
    public function update(UpdateProjectRequest $request, Project $project)
    {
        if (!auth()->check()) {
            abort(404);
        }

        $project->update($request->validated());

        return to_route('project.show', $project);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Project  $project
     * @return RedirectResponse
     */
    public function destroy(Project $project)
    {
        if (!auth()->check()) {
            abort(404);
        }

        $project->delete();

        return back();
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class AppLayout extends Component
{
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    @stack('head')

    <title>SS | {{ $title ?? config('app.name') }}</title>

{{--    ico from https://www.favicon.cc/ --}}
    <link rel="shortcut icon" href="{{ \Illuminate\Support\Facades\Vite::asset('resources/images/yeahh.ico') }}" type="image/x-icon">
    <link rel="icon" href="{{ \Illuminate\Support\Facades\Vite::asset('resources/images/yeahh.ico') }}" type="image/x-icon">

    @vite(['resources/js/app.js'])
</head>
<body class="theme-light">
<div class="page">

    @include('layouts.header')

    @include('layouts.expand')

    <div class="page-wrapper">

        <x-header :title="$header" />

        <div class="page-body">
            <div class="container-xl">
                {{ $slot }}
            </div>
        </div>

        @include('layouts.footer')

    </div>
</div>

@stack('scripts')
</body>
</html>

resources/views/layouts/expand.blade.php
<div {{ $attributes->class(['navbar-expand-md']) }}>
    <div class="collapse navbar-collapse" id="navbar-menu">
        <div class="navbar navbar-light">
            <div class="container-xl">
                <ul class="navbar-nav">

                    <x-nav-link :active="request()->routeIs('home')"
                                :href="route('home')">
                        <x-icon.profile name="Home"/>
                    </x-nav-link>

                    <x-nav-link :active="request()->routeIs('project*')"
                                :href="route('project.index')">
                        <x-icon.project name="Project"/>
                    </x-nav-link>

                </ul>
            </div>
        </div>
    </div>
</div>

resources/views/layouts/footer.blade.php
<footer class="footer footer-transparent d-print-none">
    <div class="container-xl">
        <div class="row text-center align-items-center flex-row-reverse">
            <div class="col-lg-auto ms-lg-auto">
            </div>
            <div class="col-12 col-lg-auto mt-3 mt-lg-0">
                <ul class="list-inline list-inline-dots mb-0">
                    <li class="list-inline-item">
                        Copyright © {{ now()->year }}
                        <a href="https://twitter.com/Miii49611704" class="link-secondary">HILMI AM</a>.
                        All rights reserved.
                    </li>
                    <li class="list-inline-item">
                        <a href="https://tabler.io/" class="link-secondary" rel="noopener">
                            Powered by <strong>Tabler</strong>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

resources/views/layouts/header.blade.php
<header {{ $attributes->class(['navbar navbar-expand-md navbar-dark d-print-none']) }}>
    <div class="container-xl">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-menu"
                aria-controls="navbar-menu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <h1 class="navbar-brand navbar-brand-autodark d-none-navbar-horizontal pe-0 pe-md-3">
            <a href="{{ route('home') }}">
                <img src="{{ \Illuminate\Support\Facades\Vite::asset('resources/images/hmms.png') }}" width="110"
                     height="32" alt="Tabler"
                     class="navbar-brand-image">
            </a>
        </h1>
        <div class="navbar-nav flex-row order-md-last">
            <div class="nav-item d-none d-md-flex me-3">
                <div class="btn-list">
                    <a href="https://github.com/reimiii/SUMMER-SUNSET" class="btn btn-dark" target="_blank"
                       rel="noreferrer">
                        <!-- Download SVG icon from http://tabler-icons.io/i/brand-github -->
                        <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24"
                             stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round"
                             stroke-linejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                            <path d="M9 19c-4.3 1.4 -4.3 -2.5 -6 -3m12 5v-3.5c0 -1 .1 -1.4 -.5 -2c2.8 -.3 5.5 -1.4 5.5 -6a4.6 4.6 0 0 0 -1.3 -3.2a4.2 4.2 0 0 0 -.1 -3.2s-1.1 -.3 -3.5 1.3a12.3 12.3 0 0 0 -6.2 0c-2.4 -1.6 -3.5 -1.3 -3.5 -1.3a4.2 4.2 0 0 0 -.1 3.2a4.6 4.6 0 0 0 -1.3 3.2c0 4.6 2.7 5.7 5.5 6c-.6 .6 -.6 1.2 -.5 2v3.5"></path>
                        </svg>
                        Source code
                    </a>
                    <a href="#" class="btn btn-dark" data-bs-toggle="modal" data-bs-target="#modal-report">
                        <!-- Download SVG icon from http://tabler-icons.io/i/heart -->
                        <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-address-book"
                             width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor"
                             fill="none" stroke-linecap="round" stroke-linejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                            <path d="M20 6v12a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2v-12a2 2 0 0 1 2 -2h10a2 2 0 0 1 2 2z"></path>
                            <path d="M10 16h6"></path>
                            <circle cx="13" cy="11" r="2"></circle>
                            <path d="M4 8h3"></path>
                            <path d="M4 12h3"></path>
                            <path d="M4 16h3"></path>
                        </svg>
                        Contact
                    </a>
                </div>

            </div>
            <div class="nav-item dropdown">
                <a href="#" class="nav-link d-flex lh-1 text-reset p-0"
                   @auth data-bs-toggle="dropdown" @endauth
                   @guest data-bs-toggle="modal" data-bs-target="#modal-login" @endguest
                   aria-label="Open user menu">
                    <span class="avatar avatar-sm"
                          style="background-image: url({{ $user->getAvatar() }})"></span>
                    <div class="d-none d-xl-block ps-2">
                        <div>{{ $user->name }}</div>
                        <div class="mt-1 small text-muted">{{ $user->email }}</div>
                    </div>
                </a>
                @auth
                    <div class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">

                        <a href="{{ route('profile.index', session('profile')) }}" class="dropdown-item">Manage Profile</a>
{{--                        <a href="#" class="dropdown-item">Manage Project</a>--}}
                        <div class="dropdown-divider"></div>
                        <form method="POST" action="{{ route('logout') }}">
                            @csrf
                            <a href="{{ route('logout') }}" class="dropdown-item"
                               onclick="event.preventDefault();
                                            this.closest('form').submit();">
                                Sign out
                            </a>
                        </form>
                    </div>
                @endauth
            </div>
        </div>
    </div>
</header>

<x-modal.contact/>
<x-modal.login/>

resources/views/project/create.blade.php
<x-app-layout>
    <x-slot:title>
        Create Project
    </x-slot:title>

    <x-slot:header>
        Create Project
    </x-slot:header>

    <div class="row row-cards">
        <div class="col-12">
            <form action="{{ route('project.store') }}" method="POST" class="card" enctype="multipart/form-data">
                @csrf
                <div class="card-header">
                    <h4 class="card-title">Form Create Project</h4>
                </div>

                <div class="card-body">

                    <div class="mb-3">
                        <div class="form-label">Name</div>
                        <input type="text" name="name" value="{{ old('name') }}" class="form-control">
                        @error('name')
                        <small class="form-hint text-red">{{ $message }}</small>
                        @enderror
                    </div>

                    <div class="mb-3">
                        <div class="form-label">Body</div>
                        <textarea rows="20" class="form-control" name="body">{{ old('body') }}</textarea>
                        @error('body')
                        <small class="form-hint text-red">{{ $message }}</small>
                        @enderror
                    </div>

                    <div class="mb-3">
                        <div class="form-label">Visibility</div>
                        <div>
                            <label class="form-check form-check-inline">
                                <input class="form-check-input"
                                       type="radio"
                                       value="1"
                                       name="is_public">
                                <span class="form-check-label">Public</span>
                            </label>
                            <label class="form-check form-check-inline">
                                <input class="form-check-input"
                                       checked
                                       value="0"
                                       type="radio"
                                       name="is_public">
                                <span class="form-check-label">Private</span>
                            </label>
                        </div>
                    </div>
                </div>

                <div class="card-footer text-end">
                    <div class="d-flex">
                        <button type="submit" class="btn btn-primary ms-auto">Send data</button>
                    </div>
                </div>

            </form>
        </div>
    </div>
</x-app-layout>

resources/views/project/edit.blade.php
<x-app-layout>
    <x-slot:title>
        Create Project
    </x-slot:title>

    <x-slot:header>
        {{ $project->name }} Edit
    </x-slot:header>

    <div class="row row-cards">
        <div class="col-12">
            <form action="{{ route('project.update', $project) }}" method="POST" class="card" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="card-header">
                    <h4 class="card-title">Form Edit Project</h4>
                </div>

                <div class="card-body">

                    <div class="mb-3">
                        <div class="form-label">Name</div>
                        <input type="text" name="name" value="{{ $project->name }}" class="form-control">
                        @error('name')
                        <small class="form-hint text-red">{{ $message }}</small>
                        @enderror
                    </div>

                    <div class="mb-3">
                        <div class="form-label">Body</div>
                        <textarea rows="20" class="form-control @error('body') is-invalid @enderror" name="body">{{ $project->body }}</textarea>
                        @error('body')
                        <small class="form-hint text-red">{{ $message }}</small>
                        @enderror
                    </div>

                    <div class="mb-3">
                        <div class="form-label">Visibility</div>
                        <div>
                            <label class="form-check form-check-inline">
                                <input class="form-check-input"
                                       type="radio"
                                       {{ $project->is_public ? 'checked' : '' }}
                                       value="1"
                                       name="is_public">
                                <span class="form-check-label">Public</span>
                            </label>
                            <label class="form-check form-check-inline">
                                <input class="form-check-input"
                                        {{ $project->is_public ? '' : 'checked' }}
                                       value="0"
                                       type="radio"
                                       name="is_public">
                                <span class="form-check-label">Private</span>
                            </label>
                        </div>
                    </div>
                </div>

                <div class="card-footer text-end">
                    <div class="d-flex">
                        <button type="submit" class="btn btn-primary ms-auto">Update</button>
                    </div>
                </div>

            </form>
        </div>
    </div>
</x-app-layout>

resources/views/project/index.blade.php
<x-app-layout>
    <x-slot:title>
        Project
    </x-slot:title>

    <x-slot:header>
        Project
    </x-slot:header>


    <div class="row row-cards">
        @foreach($projects as $project)
            <div class="col-md-2 col-md-4">
                <div class="card card-sm">

                    @if($project->is_public)
                        <div class="ribbon bg-green-lt">Public</div>
                    @else
                        <div class="ribbon bg-red-lt">Private</div>
                    @endif

                    <div class="card-body">
                        <a href="{{ route('project.show', $project) }}"
                           class="card-title text-black">{{ str($project->name)->limit(30) }}</a>
                        <p class="text-muted">{{ str($project->body)->limit(85) }}</p>
                    </div>

                    <div class="card-footer">
                        <div class="d-flex">
                            <a href="{{ route('project.show', $project) }}"
                               class="btn btn-ghost-info">View</a>

                            @auth()
                                <div class="ms-auto">
                                    <a href="{{ route('project.edit', $project) }}" class="btn btn-link">Edit</a>

                                    <form action="{{ route('project.destroy', $project) }}" method="POST"
                                          class="d-inline">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit"
                                                onclick="return confirm('Are you sure?')"
                                                class="btn btn-ghost-danger">Delete
                                        </button>
                                    </form>
                                </div>
                            @endauth


                        </div>

                    </div>
                </div>
            </div>
        @endforeach
    </div>

    <div class="row justify-content-center mt-3">
        <div class="pagination">
            {{ $projects->links() }}
        </div>
    </div>

    @push('scripts')

    @endpush

</x-app-layout>

resources/views/project/show.blade.php
<x-app-layout>
    <x-slot:title>
        Project Name
    </x-slot:title>

    <x-slot:header>
        {{ $project->name }}
    </x-slot:header>

    <div class="row justify-content-center">
        <div class="col-lg-10 col-xl-9">
            <div class="card card-lg">
                <div class="card-body markdown">
                    {!! str($project->body)->markdown()  !!}
                </div>
            </div>
        </div>
    </div>

</x-app-layout>